name: 'CI'
on: ['push']
jobs:
  phpSyntaxCheck:
    name: 'PHP Syntax Check'
    strategy:
      matrix:
        php_version:
          - '7.4'
          - '8.0'
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: 'actions/checkout@v2'
      - run: 'sudo update-alternatives --set php /usr/bin/php${{ matrix.php_version }}'
      - run: 'php -v'
      - run: |
          find . \( -type d \( -name '.git' -or -name 'vendor' -or -name 'runtime' \) -prune \) -or \( -type f -name '*.php' -print \) \
            | LANG=C sort \
            | xargs -n 1 php -l

  phpStyleCheck:
    name: 'PHP Coding Style'
    runs-on: 'ubuntu-20.04'
    needs:
      - 'phpSyntaxCheck'
    steps:
      - uses: 'actions/checkout@v2'
      - run: 'sudo update-alternatives --set php /usr/bin/php7.4'
      - run: 'make check-style-php'

  jsStyleCheck:
    name: 'JS Coding Style'
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'actions/setup-node@v1'
      - run: 'make check-style-js'

  cssStyleCheck:
    name: 'CSS Coding Style'
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'actions/setup-node@v1'
      - run: 'make check-style-css'
